// ============================================================
// cards.js – cards + writing, always scoped to level AND group
// ============================================================

let cardIndex=0,cardFlipped=false,cardOrder=[],activeCardLevel=null,activeCardGroup=null;
function speakGreek(text){if(!text||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(String(text));utterance.lang='el-GR';utterance.rate=.85;utterance.pitch=1;window.speechSynthesis.speak(utterance);}
function getCardPool(){let pool=activeCardLevel?getWordsForLevel(activeCardLevel):[];if(activeCardGroup)pool=pool.filter(word=>getWordGroup(word)===activeCardGroup);return pool;}
function getCurrentCard(){const pool=getCardPool();return pool[cardOrder[cardIndex]];}
function shuffleCards(){const pool=getCardPool();cardOrder=Array.from({length:pool.length},(_,i)=>i);for(let i=cardOrder.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cardOrder[i],cardOrder[j]]=[cardOrder[j],cardOrder[i]];}cardIndex=0;}
function openCards(level){activeCardLevel=level||null;activeCardGroup=null;openCardsView();}
function openCardsForGroup(group,level){activeCardLevel=level||selectedVocabularyLevel;activeCardGroup=group;openCardsView();}
function openCardsView(){const pool=getCardPool();if(!pool.length){alert('В этом уровне и группе пока нет слов.');return;}shuffleCards();showCardPage();}
function showCardPage(){const pool=getCardPool(),current=getCurrentCard();if(!current)return;const title=`${activeCardLevel}${activeCardGroup?' / '+activeCardGroup:''}`;const speechButton=`<button type="button" class="speak-word-button" onclick="speakGreek('${escapeJs(current.greek)}');event.stopPropagation()" aria-label="Listen to Greek pronunciation" title="Прослушать произношение">🔊</button>`;const html=`<div class="cards-container"><div class="cards-level-label">VOCABULARY / ${escapeHtml(title)}</div><div class="card" onclick="flipCard()"><div class="card-inner"><div class="card-front"><div class="card-level">${escapeHtml(String(current.level||'').toUpperCase())}</div><div class="card-word-row"><div class="card-word">${escapeHtml(current.greek)}</div>${speechButton}</div><div class="card-article">${escapeHtml(current.article||'')}</div></div><div class="card-back"><div class="card-level">${escapeHtml(String(current.level||'').toUpperCase())}</div><div class="card-translation">${escapeHtml(current.russian)}</div><div class="card-english">${escapeHtml(current.english||'')}</div></div></div></div><div class="memory-actions"><button class="memory-btn memory-0" onclick="rateCurrentWord(0);event.stopPropagation()">Не знаю</button><button class="memory-btn memory-1" onclick="rateCurrentWord(1);event.stopPropagation()">Сложно</button><button class="memory-btn memory-2" onclick="rateCurrentWord(2);event.stopPropagation()">Знаю</button><button class="memory-btn memory-3" onclick="rateCurrentWord(3);event.stopPropagation()">Выучено</button></div><div class="card-progress-label">Прогресс слова: ${getWordProgress(current)}/3</div><div class="card-controls"><button onclick="prevCard()">◀ Предыдущее</button><span class="card-counter">${cardIndex+1} / ${pool.length}</span><button onclick="nextCard()">Следующее ▶</button><button onclick="shuffleCards();showCardPage()">🔀 Перемешать</button><button onclick="returnFromStudy()">← Назад</button></div></div>`;renderPage('Карточки',html);cardFlipped=false;}
function rateCurrentWord(level){const current=getCurrentCard();if(!current)return;updateWordMemory(current,level);const pool=getCardPool();if(!pool.length)return;cardIndex=(cardIndex+1)%pool.length;showCardPage();}
function nextCard(){const pool=getCardPool();if(!pool.length)return;cardIndex=(cardIndex+1)%pool.length;showCardPage();}
function prevCard(){const pool=getCardPool();if(!pool.length)return;cardIndex=(cardIndex-1+pool.length)%pool.length;showCardPage();}
function flipCard(){const el=document.querySelector('.card-inner');if(!el)return;cardFlipped=!cardFlipped;el.style.transform=cardFlipped?'rotateY(180deg)':'rotateY(0deg)';}
function openWriting(level){activeCardLevel=level||null;activeCardGroup=null;openWritingView();}
function openWritingForGroup(group,level){activeCardLevel=level||selectedVocabularyLevel;activeCardGroup=group;openWritingView();}
function openWritingView(){const pool=getCardPool();if(!pool.length){alert('В этом уровне и группе пока нет слов.');return;}shuffleCards();renderWriting();}
function renderWriting(){const current=getCurrentCard(),pool=getCardPool();if(!current)return;const title=`${activeCardLevel}${activeCardGroup?' / '+activeCardGroup:''}`;const speechButton=`<button type="button" class="speak-word-button writing-speak-button" onclick="speakGreek('${escapeJs(current.greek)}')" aria-label="Listen to Greek pronunciation" title="Прослушать произношение">🔊</button>`;const html=`<div class="writing-container"><div class="cards-level-label">VOCABULARY / ${escapeHtml(title)}</div><div class="writing-prompt"><p>Переведите на греческий:</p><div class="writing-translation">${escapeHtml(current.russian)}</div><div class="writing-english">${escapeHtml(current.english||'')}</div><div class="card-level writing-level">${escapeHtml(String(current.level||'').toUpperCase())}</div></div><div class="writing-input-area"><input id="writing-input" placeholder="Введите греческое слово..." autofocus><button onclick="checkWriting()">Проверить</button></div><div id="writing-result"></div><div class="writing-answer-audio" id="writing-answer-audio">${speechButton}</div><div class="card-controls"><button onclick="prevCard();renderWriting()">◀ Предыдущее</button><span class="card-counter">${cardIndex+1} / ${pool.length}</span><button onclick="nextCard();renderWriting()">Следующее ▶</button><button onclick="shuffleCards();renderWriting()">🔀 Перемешать</button><button onclick="returnFromStudy()">← Назад</button></div></div>`;renderPage('Написание',html);document.getElementById('writing-input')?.focus();}
function checkWriting(){const input=document.getElementById('writing-input');if(!input)return;const answer=input.value.trim();if(!answer)return;const current=getCurrentCard();if(!current)return;const correct=current.greek.toLowerCase().trim()===answer.toLowerCase().trim();const result=document.getElementById('writing-result');if(result){result.className=correct?'correct':'wrong';result.textContent=correct?`✓ Правильно!  +20 pts`:`✕ Неправильно. Правильно: ${current.greek}`;}if(correct)addScore(20);updateWordMemory(current,correct?3:1);}
function escapeJs(value){return String(value??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\r?\n/g,' ');}
function returnFromStudy(){if(activeCardGroup&&activeCardLevel){selectedVocabularyLevel=activeCardLevel;openVocabularyGroup(activeCardGroup);}else openDictionary();}
